/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 hanna-landslag.gltf --transform
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/adgengi/hanna-landslag-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plane.geometry} material={materials['Material.001']} position={[93.6, 0.51, 62.17]} rotation={[0, -1.19, 0]} scale={[10, 15.78, 10]} />
      <mesh geometry={nodes.Plane001.geometry} material={materials['Material.002']} position={[101.27, -0.42, 81.6]} rotation={[0, -1.19, 0]} scale={[353.27, 3515.29, 693.41]} />
      <mesh geometry={nodes.Plane002.geometry} material={materials['Material.003']} position={[921.7, 0, -279.57]} rotation={[0, 0, -Math.PI / 2]} scale={475.96} />
    </group>
  )
}

useGLTF.preload('/adgengi/hanna-landslag-transformed.glb')
