/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 harmaborg8.gltf --transform
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Harmaborg8(props) {
  const { nodes, materials } = useGLTF('/adgengi/harmaborg8-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube002.geometry}>
        <meshBasicMaterial color={props.color} toneMapped={false} />
      </mesh>
      <mesh geometry={nodes.Cube002_1.geometry} material={materials['Material.002']} />
    </group>
  )
}

useGLTF.preload('/adgengi/harmaborg8-transformed.glb')
