/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 HjaKronunniSeeingViewNyttTest.gltf --transform
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function HjaKronunniSeeingViewNyttTest(props) {
  const { nodes, materials } = useGLTF(
    `/rafraent-veggspjald/HjaKronunniSeeingViewNyttTest-transformed.glb`,
  );
  materials['Material_0.001'].transparent = true
  materials['Material_0.001'].opacity = props.opacity
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Mesh_0.geometry}
        material={materials["Material_0.001"]}
        position={props.position}
        scale={props.scale}
      />
    </group>
  );
}

useGLTF.preload(`/rafraent-veggspjald/HjaKronunniSeeingViewNyttTest-transformed.glb`);
