/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 HjaKronunniBlindView.gltf --transform
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function HjaKronunniBlindView(props) {
  const { nodes, materials } = useGLTF("/HjaKronunniBlindView-transformed.glb");
  materials.Material_0.transparent = true;
  materials.Material_0.opacity = props.opacity;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Mesh_0.geometry}
        material={materials.Material_0}
        position={[-0.14, 0.06, -1.3]}
      />
    </group>
  );
}

useGLTF.preload("/HjaKronunniBlindView-transformed.glb");
