/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 hvittmesh.gltf --transform
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Hvittmesh(props) {
  const { nodes, materials } = useGLTF('/adgengi/hvittmesh-transformed.glb')
  // materials.Material_0.transparent = true
  // materials.Material_0.opacity = props.opacity
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_0001.geometry}>
      <meshBasicMaterial toneMapped={false} color="white" transparent opacity={props.opacity}/>
      </mesh>
    </group>
  )
}

useGLTF.preload('/adgengi/hvittmesh-transformed.glb')
