/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 linur.gltf --transform
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Linur(props) {
  const { nodes, materials } = useGLTF('/adgengi/linur-transformed.glb')
  materials.Material.transparent = true
  materials.Material.opacity = props.opacity
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Lines.geometry} material={materials.Material} />
    </group>
  )
}

useGLTF.preload('/adgengi/linur-transformed.glb')
