/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 litir.gltf --transform
*/

import React, { useRef, useState, useEffect } from "react";
import { useGLTF } from "@react-three/drei";

export function Litir(props) {
  const { nodes, materials } = useGLTF("/litir-transformed.glb");
  // materials.bleikur.visible = true;
  // materials.blar.visible = true;
  const { currentMaterial } = props;
  const [mat, setMat] = useState(undefined);
  useEffect(() => {
    console.log(currentMaterial, mat)
    if (currentMaterial == 'blar') {
      setMat(materials.bleikur);
    }
    if(currentMaterial == 'bleikur') {
      setMat(materials.bleikur);
    }
  }, [currentMaterial]);
  if (!materials) {
    return "";
  }
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Icosphere.geometry} material={mat} />
    </group>
  );
}

useGLTF.preload("/litir-transformed.glb");
