/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 Stigi.gltf --transform
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function StigiBlind(props) {
  const { nodes, materials } = useGLTF('/Stigi-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_0.geometry} material={materials['Material_0.001']} />
    </group>
  )
}

useGLTF.preload('/Stigi-transformed.glb')
