/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 linur.gltf --transform
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/linur-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Lines.geometry} material={materials.Material} />
    </group>
  )
}

useGLTF.preload('/linur-transformed.glb')
