/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 Macbook.gltf --transform
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Macbook-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Cube004_1.geometry} material={materials.base} />
        <mesh geometry={nodes.Cube004_2.geometry} material={materials.lyklabord} />
        <mesh geometry={nodes.Cube004_3.geometry} material={materials.Material} />
        <mesh geometry={nodes.Cube004_4.geometry} material={materials.gler} />
      </group>
    </group>
  )
}

useGLTF.preload('/Macbook-transformed.glb')
